<?
$aMenuLinks = Array(
    array(
        "#BUYERS#",
        "#SITE_DIR#buyers/",
        array(),
        array(),
        ""
    ),
    array(
        "#SELLERS#",
        "#SITE_DIR#sellers/",
        array(),
        array(),
        ""
    ),
    array(
        "#PARTNERS#",
        "#SITE_DIR#partners/",
        array(),
        array(),
        ""
    ),
);
?>